"""Export TinySPAN checkpoint metadata and quantized weights for RTL flow."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

os.environ.setdefault("KMP_DUPLICATE_LIB_OK", "TRUE")

import torch

from span_model import build_model


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--checkpoint", required=True)
    parser.add_argument("--scale", type=int, choices=(2, 4), required=True)
    parser.add_argument("--channels", type=int, default=48)
    parser.add_argument("--num-blocks", type=int, default=6)
    parser.add_argument("--output-dir", default="rtl/generated")
    return parser.parse_args()


def quantize_tensor(tensor: torch.Tensor) -> tuple[torch.Tensor, float]:
    tensor = tensor.detach().cpu().float()
    max_abs = float(tensor.abs().max().item())
    scale = max(max_abs / 127.0, 1e-12)
    q = torch.clamp(torch.round(tensor / scale), -128, 127).to(torch.int8)
    return q, scale


def write_mem(path: Path, q: torch.Tensor) -> None:
    flat = q.reshape(-1).to(torch.int16)
    lines = []
    for v in flat.tolist():
        lines.append(f"{v & 0xff:02x}")
    path.write_text("\n".join(lines) + "\n", encoding="ascii")


def main() -> None:
    args = parse_args()
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    weight_dir = output_dir / "weights"
    weight_dir.mkdir(parents=True, exist_ok=True)

    ckpt = torch.load(args.checkpoint, map_location="cpu")
    model = build_model(scale=args.scale, channels=args.channels, num_blocks=args.num_blocks)
    model.load_state_dict(ckpt["model"], strict=True)
    model.eval()

    manifest = []
    for name, tensor in model.state_dict().items():
        q, q_scale = quantize_tensor(tensor)
        safe_name = name.replace(".", "_")
        mem_path = weight_dir / f"{safe_name}.mem"
        write_mem(mem_path, q)
        manifest.append(
            {
                "name": name,
                "file": str(mem_path.relative_to(output_dir)).replace("\\", "/"),
                "shape": list(tensor.shape),
                "quant_scale": q_scale,
                "dtype": "int8_hex_mem",
            }
        )

    info = {
        "source_checkpoint": str(Path(args.checkpoint).resolve()),
        "scale": args.scale,
        "channels": args.channels,
        "num_blocks": args.num_blocks,
        "epoch": ckpt.get("epoch"),
        "best_psnr": ckpt.get("best_psnr"),
        "weights": manifest,
    }
    (output_dir / "tinyspan_manifest.json").write_text(json.dumps(info, indent=2), encoding="utf-8")

    vh = "\n".join(
        [
            "`ifndef TINYSPAN_MODEL_CONFIG_VH",
            "`define TINYSPAN_MODEL_CONFIG_VH",
            "// Auto-generated by train/export_tinyspan_to_rtl.py.",
            f"`define TINYSPAN_TRAINED_WEIGHTS 1",
            f"`define TINYSPAN_MODEL_SCALE {args.scale}",
            f"`define TINYSPAN_MODEL_CHANNELS {args.channels}",
            f"`define TINYSPAN_MODEL_BLOCKS {args.num_blocks}",
            f"`define TINYSPAN_WEIGHT_COUNT {len(manifest)}",
            "`endif",
            "",
        ]
    )
    (output_dir / "tinyspan_model_config.vh").write_text(vh, encoding="utf-8")
    print(f"Exported TinySPAN RTL artifacts to {output_dir}")


if __name__ == "__main__":
    main()
