create_clock -period 3.333 -name diff_clock_rtl_0_clk_p [get_ports diff_clock_rtl_0_clk_p]

set_property PACKAGE_PIN G22 [get_ports diff_clock_rtl_0_clk_p]
set_property IOSTANDARD DIFF_SSTL12 [get_ports diff_clock_rtl_0_clk_p]
set_property IOSTANDARD DIFF_SSTL12 [get_ports diff_clock_rtl_0_clk_n]

set_property PACKAGE_PIN M18 [get_ports {sw_0[0]}]
set_property PACKAGE_PIN L18 [get_ports {sw_1[0]}]
set_property IOSTANDARD LVCMOS12 [get_ports {sw_0[0]}]
set_property IOSTANDARD LVCMOS12 [get_ports {sw_1[0]}]

set_property PACKAGE_PIN R14 [get_ports {led_0[0]}]
set_property PACKAGE_PIN P13 [get_ports {led_1[0]}]
set_property PACKAGE_PIN J13 [get_ports {led_2[0]}]
set_property PACKAGE_PIN J12 [get_ports {led_3[0]}]
set_property PACKAGE_PIN B6 [get_ports {led_4[0]}]
set_property PACKAGE_PIN B5 [get_ports {led_5[0]}]
set_property PACKAGE_PIN A4 [get_ports {led_6[0]}]
set_property PACKAGE_PIN A5 [get_ports {led_7[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_3[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_4[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_5[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_6[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_7[0]}]
